### 加载数据

In [59]:
import numpy as np


X = np.load("X.npy", allow_pickle=True)

In [60]:
X[0]

[array([ 118.13705444,  115.04455566, -143.57531738,  106.43158722,
        -202.23040771,   15.26131058,   72.69781494,    7.53268862,
        -152.36148071,   51.25300598,    4.83516312,  131.07876587,
         -26.38500404,  212.60169983,  123.87007904,  189.09054565,
          64.6733017 ,   23.86533928, -124.26799011, -106.22766113,
          38.19789886,   12.2594223 ,  -16.89278793,  193.06413269,
        -213.57832336,  398.5869751 , -184.06944275,  283.11514282,
         321.16085815,   74.82887268,   25.47571564,   44.43590164,
         -41.4095726 ,  170.77433777,   42.7707634 ,   61.76328659,
         457.5423584 , -203.82702637,  -20.53711891,  269.96664429,
          63.6409111 ,  -96.36290741,  104.17526245,  -73.03527832,
          21.7961235 ,   60.83615494,  161.56401062, -236.13000488,
         315.94876099,   38.84953308,  -72.00873566,  -12.52892303,
          64.03981018, -425.89974976,  -67.8447113 , -212.28140259,
          32.74796295, -151.96824646,   47.33448

In [61]:
y = np.load("y.npy", allow_pickle=True)

In [62]:
max_len = 0
for x in X:
    if len(x) > max_len:
        max_len = len(x)

max_len

100

In [63]:
max_len = 0
for y_ in y:
    if len(y_) > max_len:
        max_len = len(y_)

max_len

100

### 键型 编码
> 将所有情况弄成一个字典

In [147]:
idx = 0
id2key = {}
key2id = {}

In [148]:
key1 = "000000"
if key1 not in key2id:
    key2id[key1] = idx
    id2key[idx] = key1
    idx += 1

In [149]:
id2key

{0: '000000'}

In [150]:
for y_ in y:
    for y__ in y_:
        key = "".join([str(int(bool(v))) for v in y__.tolist()])  # 这里简化下，就不考虑哪里用长条了。
        if key not in key2id:
            key2id[key] = idx
            id2key[idx] = key
            idx += 1

In [152]:
id2key  # 一共22种健型

{0: '000000',
 1: '000001',
 2: '001000',
 3: '100100',
 4: '001001',
 5: '010010',
 6: '101000',
 7: '010100',
 8: '010000',
 9: '100000',
 10: '000011',
 11: '100010',
 12: '000010',
 13: '000100',
 14: '000101',
 15: '011000',
 16: '100001',
 17: '001100',
 18: '110000',
 19: '001010',
 20: '010001',
 21: '000110'}

### 构造数据

准备搞一个简单的模型如下，提取一部分时序特征，一部分直接用音频特征，最后再接一个mlp
![](model1.png)

In [111]:
X_data = []
y_data = []

for i in range(len(X)):
    x_tmp = np.zeros
    x_ = np.array(X[i])
    y_ = y[i]
    print(x_.shape, len(y[i]))
    X_data[i, :x_.shape[0], :] = x_
    
    for j, y__ in enumerate(y_):
        idx = key2id["".join([str(v) for v in y__.tolist()])]
        y_data[i, j] = idx

(72, 100) 72
(96, 100) 96
(58, 100) 58
(80, 100) 80
(95, 100) 95
(80, 100) 80
(95, 100) 95
(97, 100) 97
(74, 100) 74
(23, 100) 23
(74, 100) 74
(71, 100) 71
(88, 100) 88
(78, 100) 78
(77, 100) 77
(88, 100) 88
(80, 100) 80
(73, 100) 73
(86, 100) 86
(47, 100) 47
(61, 100) 61
(92, 100) 92
(76, 100) 76
(78, 100) 78
(100, 100) 100
(99, 100) 99
(88, 100) 88
(72, 100) 72
(67, 100) 67
(95, 100) 95
(82, 100) 82
(96, 100) 96
(99, 100) 99
(55, 100) 55
(53, 100) 53
(100, 100) 100
(87, 100) 87
(86, 100) 86
(70, 100) 70
(77, 100) 77
(87, 100) 87
(72, 100) 72
(91, 100) 91
(99, 100) 99
(70, 100) 70
(43, 100) 43
(79, 100) 79
(97, 100) 97
(79, 100) 79
(75, 100) 75
(86, 100) 86
(89, 100) 89
(73, 100) 73
(30, 100) 30
(58, 100) 58
(97, 100) 97
(87, 100) 87
(85, 100) 85
(72, 100) 72
(92, 100) 92
(90, 100) 90
(99, 100) 99
(96, 100) 96
(82, 100) 82
(72, 100) 72
(73, 100) 73
(62, 100) 62
(70, 100) 70
(79, 100) 79
(81, 100) 81
(70, 100) 70
(74, 100) 74
(76, 100) 76
(82, 100) 82
(83, 100) 83
(85, 100) 85
(64, 100

In [112]:
y_data[0]

array([ 1.,  2.,  1.,  3.,  2.,  1.,  4.,  3.,  5.,  3.,  3.,  5.,  6.,
        3.,  7.,  3.,  5.,  8.,  2.,  3.,  9.,  2., 10.,  2.,  8., 11.,
        2.,  9., 12.,  7.,  9., 13.,  6., 13.,  8.,  2., 11.,  9., 13.,
        6.,  7.,  9.,  8., 13., 14., 15.,  9.,  2., 13.,  1.,  1.,  2.,
        9., 13., 13.,  9., 12.,  9., 16., 17., 18., 19., 20.,  9., 12.,
        4., 21., 22., 13.,  9., 23., 12.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [113]:
X_data.shape, y_data.shape

((415, 101, 100), (415, 101))

In [104]:
# from keras.utils import to_categorical

# y_data = to_categorical(y_data, num_classes=len(id2key))

# X_data.shape, y_data.shape

((415, 101, 100), (415, 101, 73))

### 训练模型

In [122]:
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, Dense, Embedding

# 编码器模型
encoder_inputs = Input(shape=(None, 100))
encoder_lstm = LSTM(256, return_state=True)
encoder_outputs, state_h, state_c = encoder_lstm(encoder_inputs)
encoder_states = [state_h, state_c]

# 解码器模型
decoder_inputs = Input(shape=(None,))
decoder_embeddings = Embedding(73, 256)(decoder_inputs)
decoder_lstm = LSTM(256, return_sequences=True, return_state=True)
decoder_outputs, _, _ = decoder_lstm(decoder_embeddings, initial_state=encoder_states)
decoder_dense = Dense(73, activation='softmax')(decoder_outputs)

# 构建模型
model = Model([encoder_inputs, decoder_inputs], decoder_dense)

model.summary()

Model: "model_3"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_13 (InputLayer)       [(None, None)]               0         []                            
                                                                                                  
 input_12 (InputLayer)       [(None, None, 100)]          0         []                            
                                                                                                  
 embedding_2 (Embedding)     (None, None, 256)            18688     ['input_13[0][0]']            
                                                                                                  
 lstm_20 (LSTM)              [(None, 256),                365568    ['input_12[0][0]']            
                              (None, 256),                                                  

In [123]:
# 构造解码器输入
decoder_input_data = np.zeros((415, 101))
decoder_input_data[:, 0] = 2  # 使用特殊的开始标记
decoder_input_data[:, 1:] = y_data[:, :-1]  # 目标序列向右移动一位

In [124]:
# 编译模型
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# 训练模型
model.fit([X_data, decoder_input_data], y_data, epochs=100, batch_size=64)

Epoch 1/100
7/7 [==============================] - 2s 227ms/step - loss: 4.0510 - accuracy: 0.2354
Epoch 2/100
7/7 [==============================] - 2s 279ms/step - loss: 2.9791 - accuracy: 0.2328
Epoch 3/100
7/7 [==============================] - 2s 279ms/step - loss: 2.7436 - accuracy: 0.2642
Epoch 4/100
7/7 [==============================] - 2s 275ms/step - loss: 2.6552 - accuracy: 0.2743
Epoch 5/100
7/7 [==============================] - 2s 276ms/step - loss: 2.6224 - accuracy: 0.2773
Epoch 6/100
7/7 [==============================] - 2s 274ms/step - loss: 2.6005 - accuracy: 0.2809
Epoch 7/100
7/7 [==============================] - 2s 269ms/step - loss: 2.5856 - accuracy: 0.2953
Epoch 8/100
7/7 [==============================] - 2s 274ms/step - loss: 2.5715 - accuracy: 0.2924
Epoch 9/100
7/7 [==============================] - 2s 276ms/step - loss: 2.5628 - accuracy: 0.2997
Epoch 10/100
7/7 [==============================] - 2s 274ms/step - loss: 2.5643 - accuracy: 0.2985
Epoch 11/

7/7 [==============================] - 2s 288ms/step - loss: 1.9099 - accuracy: 0.4329
Epoch 84/100
7/7 [==============================] - 2s 284ms/step - loss: 1.8996 - accuracy: 0.4356
Epoch 85/100
7/7 [==============================] - 2s 285ms/step - loss: 1.8926 - accuracy: 0.4384
Epoch 86/100
7/7 [==============================] - 2s 285ms/step - loss: 1.8840 - accuracy: 0.4402
Epoch 87/100
7/7 [==============================] - 2s 290ms/step - loss: 1.8818 - accuracy: 0.4408
Epoch 88/100
7/7 [==============================] - 2s 292ms/step - loss: 1.9043 - accuracy: 0.4349
Epoch 89/100
7/7 [==============================] - 2s 294ms/step - loss: 1.8879 - accuracy: 0.4373
Epoch 90/100
7/7 [==============================] - 2s 286ms/step - loss: 1.8684 - accuracy: 0.4446
Epoch 91/100
7/7 [==============================] - 2s 282ms/step - loss: 1.8534 - accuracy: 0.4481
Epoch 92/100
7/7 [==============================] - 2s 284ms/step - loss: 1.8431 - accuracy: 0.4522
Epoch 93/100


In [125]:
model.fit([X_data, decoder_input_data], y_data, epochs=100, batch_size=64)

Epoch 1/100
7/7 [==============================] - 2s 278ms/step - loss: 1.7630 - accuracy: 0.4768
Epoch 2/100
7/7 [==============================] - 2s 279ms/step - loss: 1.7590 - accuracy: 0.4792
Epoch 3/100
7/7 [==============================] - 2s 280ms/step - loss: 1.7460 - accuracy: 0.4804
Epoch 4/100
7/7 [==============================] - 2s 283ms/step - loss: 1.7374 - accuracy: 0.4837
Epoch 5/100
7/7 [==============================] - 2s 280ms/step - loss: 1.7416 - accuracy: 0.4822
Epoch 6/100
7/7 [==============================] - 2s 278ms/step - loss: 1.7293 - accuracy: 0.4870
Epoch 7/100
7/7 [==============================] - 2s 281ms/step - loss: 1.7150 - accuracy: 0.4928
Epoch 8/100
7/7 [==============================] - 2s 281ms/step - loss: 1.7018 - accuracy: 0.4962
Epoch 9/100
7/7 [==============================] - 2s 280ms/step - loss: 1.6858 - accuracy: 0.4997
Epoch 10/100
7/7 [==============================] - 2s 284ms/step - loss: 1.6755 - accuracy: 0.5029
Epoch 11/

7/7 [==============================] - 2s 289ms/step - loss: 1.0206 - accuracy: 0.7096
Epoch 84/100
7/7 [==============================] - 2s 287ms/step - loss: 1.0193 - accuracy: 0.7086
Epoch 85/100
7/7 [==============================] - 2s 290ms/step - loss: 1.0132 - accuracy: 0.7115
Epoch 86/100
7/7 [==============================] - 2s 290ms/step - loss: 1.0023 - accuracy: 0.7154
Epoch 87/100
7/7 [==============================] - 2s 294ms/step - loss: 0.9925 - accuracy: 0.7175
Epoch 88/100
7/7 [==============================] - 2s 289ms/step - loss: 0.9846 - accuracy: 0.7211
Epoch 89/100
7/7 [==============================] - 2s 290ms/step - loss: 0.9689 - accuracy: 0.7289
Epoch 90/100
7/7 [==============================] - 2s 292ms/step - loss: 0.9571 - accuracy: 0.7311
Epoch 91/100
7/7 [==============================] - 2s 288ms/step - loss: 0.9537 - accuracy: 0.7318
Epoch 92/100
7/7 [==============================] - 2s 285ms/step - loss: 0.9645 - accuracy: 0.7269
Epoch 93/100


## 测试下

In [139]:
X_test = np.zeros((1, 101, 100))
X_test[0] = X_data[0]

In [140]:
X_test

array([[[ 118.13705444,  115.04455566, -143.57531738, ...,
            3.55200481,   94.96218109,    6.56704664],
        [  22.9196434 ,  108.92563629,  -98.65489197, ...,
          -29.38951874,   71.6135788 ,  -18.99404335],
        [  21.9484024 ,  106.18778229,  -96.25601959, ...,
          -26.13433075,   71.57382202,  -18.51161957],
        ...,
        [   0.        ,    0.        ,    0.        , ...,
            0.        ,    0.        ,    0.        ],
        [   0.        ,    0.        ,    0.        , ...,
            0.        ,    0.        ,    0.        ],
        [   0.        ,    0.        ,    0.        , ...,
            0.        ,    0.        ,    0.        ]]])

In [141]:
# 初始化解码器输入
decoder_input = np.zeros((1, 1))
decoder_input[0, 0] = 2  # 使用特殊的开始标记

# 存储预测结果
predictions = []

# 逐步预测序列
for _ in range(101):  # 最大序列长度
    output = model.predict([X_test, decoder_input])
    prediction = np.argmax(output[:, -1, :], axis=-1)
    predictions.append(prediction[0])
    
    # 更新解码器输入
    decoder_input = np.zeros((1, 1))
    decoder_input[0, 0] = prediction[0]

y_pred = np.array(predictions)
print(y_pred)

1/1 [==============================] - 0s 10ms/step
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [46]:
y_pred = np.argmax(y_pred, axis=-1)

In [50]:
y_pred[0]

array([[0, 0, 1, 0, 0, 1],
       [0, 1, 2, 0, 0, 1],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 1, 0, 0, 1],
       [0, 1, 1, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0, 1],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0, 1],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0, 1],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
 